# Ansible Inventory - Generated by Terraform
# Generated at: ${timestamp}

[all:vars]
ansible_user=devops
ansible_ssh_private_key_file=~/.ssh/terraform_lab
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[masters]
%{ for idx, ip in master_ips ~}
${master_names[idx]} ansible_host=${ip}
%{ endfor ~}

[workers]
%{ for idx, ip in worker_ips ~}
${worker_names[idx]} ansible_host=${ip}
%{ endfor ~}

[k8s_cluster:children]
masters
workers
