# Ansible Inventory Template - Exercise 4
# Generated by Terraform at: ${timestamp}

[all:vars]
ansible_user=devops
ansible_ssh_private_key_file=~/.ssh/terraform_lab
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# TODO: Add masters group
# Use %{ for idx, ip in master_ips ~} ... %{ endfor ~} syntax
# Format: ${master_names[idx]} ansible_host=${ip}


# TODO: Add workers group
# Use same syntax as masters


# TODO: Add k8s_cluster group with children
# [k8s_cluster:children]
# masters
# workers
